name: ml_reservoir
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  ml_linalg: ^13.12.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  ml_dataframe: ^1.6.0
  ml_preprocessing: ^7.0.2

